In [1]:
from dev_utils import get_file_structure

In [2]:
print(get_file_structure('./'))

- dev_utils.py
- assets/
- main.py
- src/
    - pages/
        - __init__.py
    - data/
        - models.py
        - __init__.py
    - utils/
        - __init__.py
    - __init__.py
    - components/
        - __init__.py
        - layout.py
- commands.sh
- dev_nb.ipynb
- config.py

In [1]:
# get the currant path
import os
print(os.getcwd())

/home/yohann/projects/vlille_gcp_v2/dash_app

In [20]:
import pandas as pd
import os

from src.services.bigquery import BigQueryService
from src.data.models import Station, Record

from config import Config

os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = Config.GOOGLE_CREDENTIALS

bq = BigQueryService(Config.PROJECT, Config.DATASET, Config.TABLE_STATIONS)

query = f"""
SELECT * FROM `{Config.PROJECT}.{Config.DATASET}.{Config.TABLE_STATIONS}`
"""

stations = [Station(**row) for row in bq.query_data(query)]

df = pd.DataFrame([station.__dict__ for station in stations])
df

,id,name,adress,city,type,latitude,longitude
0,1,METROPOLE EUROPEENNE DE LILLE,MEL RUE DU BALLON,LILLE,AVEC TPE,3.075992,50.641926
1,105,VERDUN,69 AVENUE DE VERDUN,MONS EN BAROEUL,AVEC TPE,3.102310,50.638126
2,106,CONCORDE,27 BOULEVARD ALPHONSE GAYET,MONS EN BAROEUL,AVEC TPE,3.112704,50.638123
3,109,SQUARE DU PORTUGAL,FACE AU 204 RUE DE LA BASSEE,LILLE,AVEC TPE,3.030667,50.623466
4,112,SQUARE CHARLES DE GAULLE,"4, RUE FERDINAND BUISSON",HELLEMMES,AVEC TPE,3.115101,50.626846
...,...,...,...,...,...,...,...
862,253,AVENUE MILLET,1 Avenue Jean Millet,Tourcoing,AVEC TPE,50.724980,3.150884
863,254,SEBASTOPOL,FACE AU 69 RUE CARNOT,TOURCOING,SANS TPE,50.717320,3.162455
864,254,SEBASTOPOL,Face au 11 place Sébastopol,Tourcoing,AVEC TPE,50.717320,3.162455
865,255,RUE DE ROUBAIX,SECTEUR UNION,TOURCOING,SANS TPE,50.713400,3.165011
866,255,RUE DE ROUBAIX,61 Rue de Roubaix,Tourcoing,AVEC TPE,50.713400,3.165011

In [6]:
import requests
import config
import pandas as pd
import json
response = requests.get(config.Config.API_URL)

# export data to csv
data = response.text
data = json.loads(data)
# store data in a file
with open('app/data.json', 'w') as f:
    json.dump(data, f)